In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from pandas.api.types import CategoricalDtype
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [44]:
df = pd.read_csv("cr_edited.csv")
df.head()

,Soilcolor,Ph,Potassium,Phosphorus,Nitrogen,Zinc,Sulphur,Humidity-W,Humidity-Sp,Humidity-Su,...,Precipitation-W,Precipitation-Sp,Precipitation-Su,Precipitation-Au,Wind_Direction_10m_above_ground,Soil_Moisture_in_top_layer,Cloud_cover_percentage_or_amount,Range_of_wind_speed_at_2m_above_ground,Atmospheric_pressure,Crop
0,Yellowish brown,5.81,738.231,5.401,0.23,2.976000,13.816,7.993333,10.456667,11.963333,...,2.073333,5.27,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
1,Yellowish brown,5.43,606.382,10.478,0.23,3.077000,16.421,7.993333,10.456667,11.963333,...,2.073333,5.27,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
2,brown,5.41,386.580,6.847,0.23,6.611000,16.557,7.993333,10.456667,11.963333,...,2.073333,5.27,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
3,red,5.65,207.086,3.418,0.23,0.460181,16.075,7.993333,10.456667,11.963333,...,2.073333,5.27,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley
4,red,5.27,317.357,39.282,0.23,2.743000,12.558,7.993333,10.456667,11.963333,...,2.073333,5.27,12.303333,5.27,3.44,0.73,56.57,6.24,77.03,Barley

In [45]:
df.shape

(3867, 29)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3867 entries, 0 to 3866
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Soilcolor                               3867 non-null   object
 1   Ph                                      3867 non-null   float64
 2   Potassium                               3867 non-null   float64
 3   Phosphorus                              3867 non-null   float64
 4   Nitrogen                                3867 non-null   float64
 5   Zinc                                    3867 non-null   float64
 6   Sulphur                                 3867 non-null   float64
 7   Humidity-W                              3867 non-null   float64
 8   Humidity-Sp                             3867 non-null   float64
 9   Humidity-Su                             3867 non-null   float64
 10  Humidity-Au                             3867 non-null   float64
 11  Air_Temperature_MAX-W                   3867 non-null   float64
 12  Air_Temperature_MAX-Sp                  3867 non-null   float64
 13  Air_Temperature_MAX-Su                  3867 non-null   float64
 14  Air_Temperature_MAX-Au                  3867 non-null   float64
 15  Air_Temperature_MIN-W                   3867 non-null   float64
 16  Air_Temperature_MIN-Sp                  3867 non-null   float64
 17  Air_Temperature_MIN-Su                  3867 non-null   float64
 18  Air_Temperature_MIN-Au                  3867 non-null   float64
 19  Precipitation-W                         3867 non-null   float64
 20  Precipitation-Sp                        3867 non-null   float64
 21  Precipitation-Su                        3867 non-null   float64
 22  Precipitation-Au                        3867 non-null   float64
 23  Wind_Direction_10m_above_ground         3867 non-null   float64
 24  Soil_Moisture_in_top_layer              3867 non-null   float64
 25  Cloud_cover_percentage_or_amount        3867 non-null   float64
 26  Range_of_wind_speed_at_2m_above_ground  3867 non-null   float64
 27  Atmospheric_pressure                    3867 non-null   float64
 28  Crop                                    3867 non-null   object
dtypes: float64(27), object(2)
memory usage: 876.2+ KB

In [47]:
df.isna().sum()

Soilcolor                                 0
Ph                                        0
Potassium                                 0
Phosphorus                                0
Nitrogen                                  0
Zinc                                      0
Sulphur                                   0
Humidity-W                                0
Humidity-Sp                               0
Humidity-Su                               0
Humidity-Au                               0
Air_Temperature_MAX-W                     0
Air_Temperature_MAX-Sp                    0
Air_Temperature_MAX-Su                    0
Air_Temperature_MAX-Au                    0
Air_Temperature_MIN-W                     0
Air_Temperature_MIN-Sp                    0
Air_Temperature_MIN-Su                    0
Air_Temperature_MIN-Au                    0
Precipitation-W                           0
Precipitation-Sp                          0
Precipitation-Su                          0
Precipitation-Au                          0
Wind_Direction_10m_above_ground           0
Soil_Moisture_in_top_layer                0
Cloud_cover_percentage_or_amount          0
Range_of_wind_speed_at_2m_above_ground    0
Atmospheric_pressure                      0
Crop                                      0
dtype: int64

In [48]:
df.describe()

,Ph,Potassium,Phosphorus,Nitrogen,Zinc,Sulphur,Humidity-W,Humidity-Sp,Humidity-Su,Humidity-Au,...,Air_Temperature_MIN-Au,Precipitation-W,Precipitation-Sp,Precipitation-Su,Precipitation-Au,Wind_Direction_10m_above_ground,Soil_Moisture_in_top_layer,Cloud_cover_percentage_or_amount,Range_of_wind_speed_at_2m_above_ground,Atmospheric_pressure
count,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,...,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000,3867.000000
mean,5.857295,324.284770,11.349588,0.179153,1.774094,11.311625,8.346870,9.082508,12.232020,10.990747,...,8.934315,1.555862,4.023404,14.517500,4.762687,71.579444,0.709028,51.630709,8.262413,78.426168
std,0.676690,202.250133,34.141864,0.066476,1.460809,5.542094,0.613948,0.790654,0.894970,0.993861,...,2.046221,0.691682,1.117531,4.111199,1.394398,80.929898,0.055355,16.328656,9.661188,2.380380
min,4.300000,41.134000,0.000000,0.000262,0.100000,0.050000,7.183333,7.650000,10.476667,9.070000,...,3.980000,0.000000,1.940000,4.836667,2.156667,0.060000,0.520000,0.460000,4.860000,74.170000
25%,5.390000,191.000000,2.000000,0.131200,1.100000,7.305000,7.933333,8.403333,11.430000,10.150000,...,8.260000,0.910000,3.246667,11.866667,3.463333,36.060000,0.690000,48.620000,5.410000,77.150000
50%,5.780000,282.000000,4.000000,0.179884,1.500000,10.700000,8.383333,9.340000,12.166667,10.926667,...,8.380000,1.736667,4.410000,16.620000,5.430000,68.940000,0.730000,59.110000,6.010000,78.250000
75%,6.200000,405.000000,7.920000,0.230000,2.060000,14.195500,8.910000,9.480000,12.836667,11.433333,...,10.700000,2.073333,5.203333,17.816667,5.823333,88.310000,0.740000,59.110000,6.240000,79.610000
max,8.500000,2119.000000,782.000000,0.695600,45.500000,118.347000,9.723333,10.703333,13.853333,12.800000,...,13.643333,2.780000,5.660000,19.920000,7.420000,354.880000,0.800000,59.110000,46.100000,83.760000

In [49]:
float_features = df.select_dtypes(include=["float64"]).columns

print("Total number of float features : ", float_features.shape[0])
print("Integer Features Names: ", float_features.tolist())

Total number of float features :  27
Integer Features Names:  ['Ph', 'Potassium', 'Phosphorus', 'Nitrogen', 'Zinc', 'Sulphur', 'Humidity-W', 'Humidity-Sp', 'Humidity-Su', 'Humidity-Au', 'Air_Temperature_MAX-W', 'Air_Temperature_MAX-Sp', 'Air_Temperature_MAX-Su', 'Air_Temperature_MAX-Au', 'Air_Temperature_MIN-W', 'Air_Temperature_MIN-Sp', 'Air_Temperature_MIN-Su', 'Air_Temperature_MIN-Au', 'Precipitation-W', 'Precipitation-Sp', 'Precipitation-Su', 'Precipitation-Au', 'Wind_Direction_10m_above_ground', 'Soil_Moisture_in_top_layer', 'Cloud_cover_percentage_or_amount', 'Range_of_wind_speed_at_2m_above_ground', 'Atmospheric_pressure']

In [50]:
cat_features = df.select_dtypes(include=["object"]).columns

print("Total number of categorical features : ", cat_features.shape[0])
print("Integer Features Names: ", cat_features.tolist())

Total number of categorical features :  2
Integer Features Names:  ['Soilcolor', 'Crop']

In [51]:
df['Soilcolor'] = df['Soilcolor'].str.lower()

In [52]:
df["Soilcolor"] = df["Soilcolor"].replace('Red', 'red')
df["Soilcolor"] = df["Soilcolor"].replace('Brown', 'brown')
df["Soilcolor"] = df["Soilcolor"].replace('Black', 'black')
df["Soilcolor"] = df["Soilcolor"].replace('redish brown', 'reddish brown')
df["Soilcolor"] = df["Soilcolor"].replace('reddis brown', 'reddish brown')
df["Soilcolor"] = df["Soilcolor"].replace('reddish brown;moist', 'reddish brown')
df["Soilcolor"] = df["Soilcolor"].replace('reddish broown', 'reddish brown')
df["Soilcolor"] = df["Soilcolor"].replace('redishbrown', 'reddish brown')
df["Soilcolor"] = df["Soilcolor"].replace('darkbrown', 'dark brown')
df["Soilcolor"] = df["Soilcolor"].replace('replacement of inaccessible target red;luvisols', 'red;luvisols')
df["Soilcolor"] = df["Soilcolor"].replace('dark greyish brown', 'dark grayish brown')

In [53]:
# Create a dictionary to correct spelling mistakes
spelling_corrections = {
    'lihgtish brown': 'lightish brown',
    'perl brown': 'pearl brown',
    'dark greyish brown': 'dark grayish brown',
    'grayish brown (gb)': 'grayish brown',
    'reddish' : 'red',
    'dark grayish':'dark gray',
    'black;vertisol':'black'
    
}

# Replace misspelled entries
df["Soilcolor"] = df["Soilcolor"].replace(spelling_corrections)

In [55]:
# Create a mapping dictionary for replacements
color_mapping = {
    'Red': 'red',
    'reddish': 'reddish',
    'reddish brown': 'reddish brown',
    'dark reddish brown': 'dark reddish brown',
    'very dark brown': 'very dark brown',
    'dark brown': 'dark brown',
    'yellowish brown': 'yellowish brown',
    'grayish brown': 'grayish brown',
    'dark grayish brown': 'dark grayish brown',
    'dark greyish brown': 'dark grayish brown',
    'gray': 'gray',
    'dark gray': 'dark gray',
    'very dark gray': 'very dark gray',
    'reddish gray': 'reddish gray',
    'light red': 'light red',
    'red brown': 'reddish brown',
    'lihgtish brown': 'lightish brown',
    'perl brown': 'pearl brown',
    'replacement of inaccessible target red;luvisols': 'red',
    'red;luvisols': 'red',
    'black;vertisol': 'black',
}

# Replace values in the Soilcolor column
df["Soilcolor"] = df["Soilcolor"].replace(color_mapping)

In [56]:
df["Soilcolor"].value_counts()

Soilcolor
brown                 1302
red                   1210
black                  868
other                  128
reddish brown          114
gray                    88
dark brown              70
dark gray               38
dark reddish brown      13
very dark brown         11
yellowish brown          7
grayish brown            6
dark grayish brown       4
reddish gray             2
very dark gray           2
light red                1
pearl brown              1
dark red                 1
lightish brown           1
Name: count, dtype: int64

In [57]:
df["Crop"].value_counts()

Crop
Teff          1260
Maize          732
Wheat          715
Barley         503
Bean           253
Pea             94
Sorghum         72
Dagussa         71
Niger seed      64
Potato          48
Red Pepper      29
Fallow          26
Name: count, dtype: int64

In [58]:
df.to_csv("cr.csv")